version: "3.9"

services:
  bloom-venom-api:
    build: .
    container_name: bloom-venom-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TOKENIZERS_PARALLELISM=false
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4g
